# Generated by Django 4.2 on 2024-01-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='price',
            field=models.FloatField(default=0, max_length=(15, 2)),
        ),
    ]
