# Generated by Django 4.2 on 2024-01-16 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fisherman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('phone', models.CharField(max_length=11, verbose_name='Phone')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('fish_qty', models.FloatField(verbose_name='Quantity')),
                ('fisherman_bill', models.FloatField(verbose_name='Bill')),
                ('other_cost', models.FloatField(verbose_name='Other Cost')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_harvests', to=settings.AUTH_USER_MODEL)),
                ('fisherman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvests', to='fisheries.fisherman')),
            ],
        ),
    ]
