# Generated by Django 4.2 on 2023-12-30 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(max_length=6, verbose_name='Amount')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, choices=[('MANAGER', 'Manager'), ('SALESMAN', 'Salesman'), ('FARMER', 'Farmer')], max_length=20, null=True, verbose_name='Designation')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Phone')),
                ('salary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_staffs', to='staffs.salary')),
            ],
        ),
    ]
