# Generated by Django 4.2 on 2024-01-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0003_staff_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='address',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='staff',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='nid',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='NID'),
        ),
    ]
